version: "3"

services:
  api:
    env_file:
      "./api/.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    container_name: app-api

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: app-client
