version: "3"

services:
  api:
    image: yavilavi/toolbox-technical-test-api
    env_file:
      "./api/.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    container_name: app-api

  client:
    image: yavilavi/toolbox-technical-test-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: app-client
